#include "EOSUserInterface_LinkEOSAccountsAgainstCrossPlatform_Context.h"

void UEOSUserInterface_LinkEOSAccountsAgainstCrossPlatform_Context::SelectedCandidates(TArray<FEOSUserInterface_CandidateEOSAccount> NewSelectedCandidates) {
}

UEOSUserInterface_LinkEOSAccountsAgainstCrossPlatform_Context::UEOSUserInterface_LinkEOSAccountsAgainstCrossPlatform_Context() {
}

