#include "EOSUserInterface_SwitchToCrossPlatformAccount_Context.h"

void UEOSUserInterface_SwitchToCrossPlatformAccount_Context::SelectChoice(EEOSUserInterface_SwitchToCrossPlatformAccount_Choice SelectedChoice) {
}

UEOSUserInterface_SwitchToCrossPlatformAccount_Context::UEOSUserInterface_SwitchToCrossPlatformAccount_Context() {
}

